# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nice_nano_v2
    shield: skeletyl_v2_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: skeletyl_v2_right
  - board: nice_nano_v2
    shield: charybdis_4x6_v2_left
  - board: nice_nano_v2
    shield: charybdis_4x6_v2_right
  - board: nice_nano_v2
    shield: luna_left
  - board: nice_nano_v2
    shield: luna_right
  - board: nice_nano_v2
    shield: rollow_left
  - board: nice_nano_v2
    shield: rollow_right
  - board: nice_nano_v2
    shield: two_percent_milk
  - board: nice_nano_v2
    shield: settings_reset
